### ISSUE TITLE
Illustrate the use of : operator

### ISSUE THREAD

**Issue by djhunter** [UCSBCarpentry/CustomDC-R#11]
After it says

> In pivoting longer, we also need to specify what columns to reshape. If the columns are directly adjacent as they are here, we don’t even need to list the all out: we can just use the : operator!

the example that follows doesn't use the : operator. After Issue #10 is resolved, you can do this:

```r
penguins_long <- penguins_wide %>%
  pivot_longer(names_to = "sex", 
               values_to = "mean_body_mass_g", 
               cols = female:unknown)
```

**Comment by apandas** [comment]
resolved with commit [5f434fd](https://github.com/UCSBCarpentry/CustomDC-R/commit/5f434fd2d40f5a051f395b37df9b48439b108ef2)
