### ISSUE TITLE
Wrong variable name in Ep4 Challenge 1

### ISSUE THREAD

**Issue by djhunter** [UCSBCarpentry/CustomDC-R#3]
In the first challenge of episode 4, the new column should be called `flipper_length_cm`, not `flipper_length_mm`. This needs to be changed in both the question and in the solution.

**Comment by apandas** [comment]
resolved with commit [78dbf88](https://github.com/UCSBCarpentry/CustomDC-R/commit/78dbf8868c9b851b66fd3a32140f01f8b8c8ab6f)
