### ISSUE TITLE
Numbered list formatting

### ISSUE THREAD

**Issue by djhunter** [UCSBCarpentry/CustomDC-R#7]
At the beginning of the Reshaping section, the numbered list isn't formatted properly. It looks like this on the webpage:

1 Each variable has its own column

  1. Each observation has its own row
  2. Each value must have its own cell
  3. Each type of observational unit forms a table Here we examine the fourth rule: Each type of observational unit forms a table.

**Comment by apandas** [comment]
resolved with commit [78dbf88](https://github.com/UCSBCarpentry/CustomDC-R/commit/78dbf8868c9b851b66fd3a32140f01f8b8c8ab6f)
