### ISSUE TITLE
No "gif below"

### ISSUE THREAD

**Issue by djhunter** [UCSBCarpentry/CustomDC-R#8]
No image appears after the following sentence:

> The gif below shows how these two formats relate to each other, and gives you an idea of how we can use R to shift from one format to the other.

**Comment by apandas** [comment]
Resolved by adding in gif with commit [5f434fd](https://github.com/UCSBCarpentry/CustomDC-R/commit/5f434fd2d40f5a051f395b37df9b48439b108ef2)
